---
title: "Redes Multinomiales"
author: "Gustavo Andrés Aguilar Torreblanca"
format:
  html: 
    toc: true
    html-math-method: katex
    ebed-resources: true
    self-contained-math: true
    df-print: kable
editor: source
---

```{r}
library(bnlearn)
```

```{r}
data = read.csv("../data/survey.csv", stringsAsFactors = TRUE)
head(data)
```
```{r}
dag = empty.graph(nodes = c("A", "S", "E", "O", "R", "T"))
```

```{r}
arc_set = matrix(c("A", "E",
                   "E", "O",
                   "E", "R",
                   "O", "T",
                   "R", "T",
                   "S", "E"), byrow = TRUE, ncol = 2,
                 dimnames = list(NULL, c("from", "to")))
```

```{r}
arcs(dag) = arc_set
```

```{r}
dag
```

```{r}
bn_mle = bn.fit(dag, data = data, method = "mle")
```

```{r}
bn_mle$O
```

```{r}
ci.test("T", "E", c("O", "R"), test = "mi", data = data)
```

```{r}
ci.test("T", "E", c("O", "R"), test = "x2", data = data)
```

```{r}
ci.test("T", "O", "R", test = "mi", data = data)
```
```{r}
ci.test("T", "O", "R", test = "x2", data = data)
```


```{r}
arc.strength(dag, data = data, criterion = "mi")
```

```{r}
score(dag, data = data, type = "bic")
```

```{r}
score(dag, data = data, type = "aic")
```


